### ISSUE TITLE
About this Example - Error

### ISSUE THREAD

**Issue by jlzcardoso** [dotnet/docs.pt-br#108]
The compiler complains about this line and do not compile.

  // Cause the OnRegionChange delegate to be called.
    elemHost.Region = new Region()

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 271ce87d-14af-50b6-4f7a-c6d86fff338b
* Version Independent ID: 98d164bb-5dff-af9c-beb0-441d750eb06d
* Content: [Instruções passo a passo: mapeando propriedades usando o controle ElementHost](https://docs.microsoft.com/pt-br/dotnet/framework/wpf/advanced/walkthrough-mapping-properties-using-the-elementhost-control)
* Content Source: [docs/framework/wpf/advanced/walkthrough-mapping-properties-using-the-elementhost-control.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/framework/wpf/advanced/walkthrough-mapping-properties-using-the-elementhost-control.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #10050](https://github.com/dotnet/docs/issues/10050) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @jlzcardoso 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
