### ISSUE TITLE
Docker file COPY

### ISSUE THREAD

**Issue by rochar** [dotnet/docs.pt-br#111]
In the Docker File the COPY instruction should be replace by the ADD for the latest docker version

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 72ef1481-3b6f-30bf-330d-45400c0a349c
* Version Independent ID: 03a156f7-b178-4d54-503d-26d229f89dcd
* Content: [Colocar um aplicativo em contêiner com o Docker](https://docs.microsoft.com/pt-br/dotnet/core/docker/docker-basics-dotnet-core)
* Content Source: [docs/core/docker/docker-basics-dotnet-core.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/core/docker/docker-basics-dotnet-core.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **johnalex**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #10416](https://github.com/dotnet/docs/issues/10416) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @rochar 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/10416.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
